### ISSUE TITLE
handling missing igraph

### ISSUE THREAD

**Issue by yy** [Hoosier-Clusters/clusim#15]
https://github.com/ajgates42/clusim/blob/f06e58fdf5a8b664fe7887c6336d82421094f8fa/clusim/clusimelement.py#L9

If nothing is done when igraph module is missing, it will produce errors down the line (e.g. the test doesn't work if you don't have igraph). Add igraph as a dependency?

**Comment by ajgates42** [comment]
python-graph is now a dependency
