### ISSUE TITLE
Several inconsistencies in the docstrings / package

### ISSUE THREAD

**Issue by jg-you** [Hoosier-Clusters/clusim#28]
I'm still preparing the PR for the Reduced Mutual Information---expect it soon.

In doing so I've noticed a number of inconsistencies.
For example, there are arguments not defined in docstrings, e.g., logbase in expected_mi. 
The list `available_similarity_measures` in sim.py, is not up to date.
clumsim.ref is also out of date (and the style is inconsistent between refs).

I will avoid fixing these in my upcoming PR, to separate the contributions nicely.
But I can put in a second one afterwards if that's helpful.

**Comment by ajgates42** [comment]
Thanks for finding these inconsistencies, it would definitely be helpful to have a second PR to clean things up.

**Comment by jg-you** [comment]
Closed by Pull request #33
