### ISSUE TITLE
Clustering constructor is fickle

### ISSUE THREAD

**Issue by jg-you** [Hoosier-Clusters/clusim#30]
Last issue I swear!
While testing the code for PR #29 , I noticed that the constructor of the `Clustering` object is _very_ sensitive to the type of input given.

For example, when I construct a clustering from the following dictionary mapping clusters to elements 

    x = {0: [0,1,2,3,4], 1:[5,6,7,8,9]}
    clu  = Clustering(clu2elm_dict=x)   

no warning are raised, yet a bunch of functions in the `sim` subpackage break down, because they expect a dictionary of *sets*.

I think that it would be easy to cast all iterables to sets at construction time, but I don't know whether this would affect other parts of the code?

**Comment by ajgates42** [comment]
Geez!  I guess close to release I started to get sloppy ; ). I'll take another pass to clean things up.

**Comment by jg-you** [comment]
Nice! 
While at it, it would probably be useful to support scikit style construction with clusterings declared as 
`[0,0,0,0,0,0,1,1,1,0,0,0]` etc. I can put a PR in for that.
