### ISSUE TITLE
Problem on from_scipy_linkage

### ISSUE THREAD

**Issue by jisungyoon** [Hoosier-Clusters/clusim#34]
Hi, I am jisung.
I tried to use clusim with linkage results, but I think from_scipy_linkage does not work properly.

![Screen Shot 2020-02-06 at 2 52 34 PM](https://user-images.githubusercontent.com/10040328/73973381-732e8180-48f0-11ea-8753-0bcb25431873.png)

I think there should be the part that assigns .is_hierarchical as true in the from_scipy_linkage method.

**Comment by ajgates42** [comment]
Yup, you're completely correct.  I've just updated the from_scipy_linkage function, as well as fixed a few other bugs with hierarchical clustering comparisons in general.  Hope that helps!
