### ISSUE TITLE
sphinx conf.py has a local path

### ISSUE THREAD

**Issue by yy** [Hoosier-Clusters/clusim#9]
https://github.com/ajgates42/clusim/blob/4c6251836689be3e15e93fbe8b5da10123a9b5fa/docs/source/conf.py#L21

**Comment by ajgates42** [comment]
whoops!  thats gone now

**Comment by yy** [comment]
I think the best practice is creating a pull request addressing each issue and refer it from the issue. (e.g. "pull req #xx fixes this issue")
